---
apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-rego
  annotations:
    # xrender will try to talk to your Function at localhost:9443
    xrender.crossplane.io/runtime: Development
    xrender.crossplane.io/runtime-development-target: localhost:9443